build:
    tags:
        - dnsutils
        - ifstat
        - linux
        - libpam0g-dev
        - nodejs
        - traceroute
        - vagrant
        - virtualbox
    script:
        - vagrant box update
        - vagrant up        
        - vagrant destroy --force
