stages:
  - Build

ubuntu-18.04_amd64-docker:
  stage: Build
  tags:
    - docker
    - x86_64
  script:
    - docker build -f installers/blur-monitor_ubuntu-18.04_amd64/Dockerfile .
  after_script:
    - docker rm blur-monitor-build-ubuntu-18.04

debian-9_amd64-docker:
  stage: Build
  tags:
    - docker
    - x86_64
  script:
    - docker build -f installers/blur-monitor_debian-9_amd64/Dockerfile .
  after_script:
    - docker rm blur-monitor-build-debian-9

ubuntu-16.04_amd64-docker:
  stage: Build
  tags:
    - docker
    - x86_64
  script:
    - docker build -f installers/blur-monitor_ubuntu-16.04_amd64/Dockerfile .
  after_script:
    - docker rm blur-monitor-build-ubuntu-16.04
