build:
    tags:
        - dnsutils
        - ifstat
        - linux
        - libpam0g-dev
        - nodejs
        - traceroute
        - vagrant
        - virtualbox
    script:
        - vagrant box update
        - vagrant up bionic
        - vagrant destroy --force bionic
    artifacts:
        paths:
            - installers/blur-monitor_ubuntu-18.04_amd64.deb
        expire_in: 1 week
