build:
    tags:
        - linux
        - nodejs
        - dnsutils
        - ifstat
        - traceroute
        - libpam0g-dev
    script:
        - npm install
        - npm run installer:ubuntu-18.04_amd64
