build:
    tags:
        - linux
        - nodejs
        - bower
        - dnsutils
        - ifstat
        - traceroute
        - libpam0g-dev
    script:
        - npm install
        - npm run build:binary
